name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - markdown-preview-vera.css
  workflow_dispatch:

permissions:
  contents: read

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Markdown Preview Vera stylesheet
        run: |
          curl --fail --show-error --silent \
            "https://purge.jsdelivr.net/gh/Abdulrahman-Elsmmany/markdown-preview-settings@main/markdown-preview-vera.css"
